version: "3.9"
services:
  home:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      - ./:/app
    command: npm run dev
  cart:
    build: ./apps/cart
    working_dir: /app
    ports:
      - "3001:3000"
    volumes:
      - ./apps/cart:/app
    command: npm run dev

